#Independent settings for the local costmap
local_costmap:
    publish_voxel_map: false
    global_frame: odom
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 5.0
    static_map: false
    rolling_window: true
    width: 12.0
    height: 12.0
    resolution: 0.05
    origin_x: -3.0
    origin_y: 0.0
