controller_frequency: 10.0
controller_patience:  60.0
planner_patience:  60.0
planner_frequency: 50.0
clearing_radius: 0.4
footprint_padding: 0.01
#oscillation_timeout: 10.0
#oscillation_distance: 0.5
