map_type: costmap
transform_tolerance: 0.3

inflation_radius: 0.7
footprint: [[-0.65, -0.4], [-0.65, 0.4], [0.65, 0.4],[0.65, -0.4]]
observation_sources: base_scan

base_scan: {
            data_type: LaserScan,
            topic: base_scan,
            expected_update_rate: 0.4,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0,
            max_obstacle_range: 6.0}
