/* Auto-generated by genmsg_cpp for file /home/artur/ros_works/roswheelchair/trunk/ros/stacks/inria_wheelchair/social_filter/msg/humanSocialSpaces.msg */
#ifndef SOCIAL_FILTER_MESSAGE_HUMANSOCIALSPACES_H
#define SOCIAL_FILTER_MESSAGE_HUMANSOCIALSPACES_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "social_filter/humanSocialSpace.h"

namespace social_filter
{
template <class ContainerAllocator>
struct humanSocialSpaces_ {
  typedef humanSocialSpaces_<ContainerAllocator> Type;

  humanSocialSpaces_()
  : socialSpaces()
  {
  }

  humanSocialSpaces_(const ContainerAllocator& _alloc)
  : socialSpaces(_alloc)
  {
  }

  typedef std::vector< ::social_filter::humanSocialSpace_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanSocialSpace_<ContainerAllocator> >::other >  _socialSpaces_type;
  std::vector< ::social_filter::humanSocialSpace_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::humanSocialSpace_<ContainerAllocator> >::other >  socialSpaces;


  typedef boost::shared_ptr< ::social_filter::humanSocialSpaces_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::social_filter::humanSocialSpaces_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct humanSocialSpaces
typedef  ::social_filter::humanSocialSpaces_<std::allocator<void> > humanSocialSpaces;

typedef boost::shared_ptr< ::social_filter::humanSocialSpaces> humanSocialSpacesPtr;
typedef boost::shared_ptr< ::social_filter::humanSocialSpaces const> humanSocialSpacesConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::social_filter::humanSocialSpaces_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::social_filter::humanSocialSpaces_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace social_filter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::social_filter::humanSocialSpaces_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::social_filter::humanSocialSpaces_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::social_filter::humanSocialSpaces_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5f9825a90c7f72b892aaab742bafc102";
  }

  static const char* value(const  ::social_filter::humanSocialSpaces_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5f9825a90c7f72b8ULL;
  static const uint64_t static_value2 = 0x92aaab742bafc102ULL;
};

template<class ContainerAllocator>
struct DataType< ::social_filter::humanSocialSpaces_<ContainerAllocator> > {
  static const char* value() 
  {
    return "social_filter/humanSocialSpaces";
  }

  static const char* value(const  ::social_filter::humanSocialSpaces_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::social_filter::humanSocialSpaces_<ContainerAllocator> > {
  static const char* value() 
  {
    return "humanSocialSpace[] socialSpaces\n\
\n\
================================================================================\n\
MSG: social_filter/humanSocialSpace\n\
Header header\n\
\n\
int32 id\n\
int32 human_id\n\
float32 size\n\
float32 sigma_h\n\
float32 sigma_r\n\
float32 sigma_s\n\
int32   attractiveness\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::social_filter::humanSocialSpaces_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::social_filter::humanSocialSpaces_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.socialSpaces);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct humanSocialSpaces_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::social_filter::humanSocialSpaces_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::social_filter::humanSocialSpaces_<ContainerAllocator> & v) 
  {
    s << indent << "socialSpaces[]" << std::endl;
    for (size_t i = 0; i < v.socialSpaces.size(); ++i)
    {
      s << indent << "  socialSpaces[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::social_filter::humanSocialSpace_<ContainerAllocator> >::stream(s, indent + "    ", v.socialSpaces[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOCIAL_FILTER_MESSAGE_HUMANSOCIALSPACES_H

