/* Auto-generated by genmsg_cpp for file /home/arturo/ros_works/roswheelchair/trunk/ros/stacks/inria_wheelchair/social_filter/msg/int_list.msg */
#ifndef SOCIAL_FILTER_MESSAGE_INT_LIST_H
#define SOCIAL_FILTER_MESSAGE_INT_LIST_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "social_filter/int_data.h"

namespace social_filter
{
template <class ContainerAllocator>
struct int_list_ {
  typedef int_list_<ContainerAllocator> Type;

  int_list_()
  : header()
  , formation()
  {
  }

  int_list_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , formation(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector< ::social_filter::int_data_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::int_data_<ContainerAllocator> >::other >  _formation_type;
  std::vector< ::social_filter::int_data_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::social_filter::int_data_<ContainerAllocator> >::other >  formation;


  typedef boost::shared_ptr< ::social_filter::int_list_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::social_filter::int_list_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct int_list
typedef  ::social_filter::int_list_<std::allocator<void> > int_list;

typedef boost::shared_ptr< ::social_filter::int_list> int_listPtr;
typedef boost::shared_ptr< ::social_filter::int_list const> int_listConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::social_filter::int_list_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::social_filter::int_list_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace social_filter

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::social_filter::int_list_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::social_filter::int_list_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::social_filter::int_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "8c6dca5d36f6382490c6b1f8163c65b0";
  }

  static const char* value(const  ::social_filter::int_list_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x8c6dca5d36f63824ULL;
  static const uint64_t static_value2 = 0x90c6b1f8163c65b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::social_filter::int_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "social_filter/int_list";
  }

  static const char* value(const  ::social_filter::int_list_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::social_filter::int_list_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int_data[] formation \n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: social_filter/int_data\n\
uint8 type\n\
uint8[] id_members\n\
float32 media_x\n\
float32 media_y\n\
float32 sd_x\n\
float32 sd_y\n\
float32 angle\n\
float32[] meet_points\n\
 \n\
\n\
";
  }

  static const char* value(const  ::social_filter::int_list_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::social_filter::int_list_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::social_filter::int_list_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::social_filter::int_list_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.formation);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct int_list_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::social_filter::int_list_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::social_filter::int_list_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "formation[]" << std::endl;
    for (size_t i = 0; i < v.formation.size(); ++i)
    {
      s << indent << "  formation[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::social_filter::int_data_<ContainerAllocator> >::stream(s, indent + "    ", v.formation[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // SOCIAL_FILTER_MESSAGE_INT_LIST_H

