/* Auto-generated by genmsg_cpp for file /home/arturo/ros_works/pal/pal-ros-pkg/pal_msgs/msg/PoseWithVelocity.msg */
#ifndef PAL_MSGS_MESSAGE_POSEWITHVELOCITY_H
#define PAL_MSGS_MESSAGE_POSEWITHVELOCITY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "geometry_msgs/Pose2D.h"

namespace pal_msgs
{
template <class ContainerAllocator>
struct PoseWithVelocity_ {
  typedef PoseWithVelocity_<ContainerAllocator> Type;

  PoseWithVelocity_()
  : header()
  , pose()
  , vx(0.0)
  , vy(0.0)
  {
  }

  PoseWithVelocity_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , pose(_alloc)
  , vx(0.0)
  , vy(0.0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
   ::geometry_msgs::Pose2D_<ContainerAllocator>  pose;

  typedef double _vx_type;
  double vx;

  typedef double _vy_type;
  double vy;


  typedef boost::shared_ptr< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pal_msgs::PoseWithVelocity_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct PoseWithVelocity
typedef  ::pal_msgs::PoseWithVelocity_<std::allocator<void> > PoseWithVelocity;

typedef boost::shared_ptr< ::pal_msgs::PoseWithVelocity> PoseWithVelocityPtr;
typedef boost::shared_ptr< ::pal_msgs::PoseWithVelocity const> PoseWithVelocityConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::pal_msgs::PoseWithVelocity_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace pal_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::pal_msgs::PoseWithVelocity_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "681693b69512b49b14b75524f5ffd1aa";
  }

  static const char* value(const  ::pal_msgs::PoseWithVelocity_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x681693b69512b49bULL;
  static const uint64_t static_value2 = 0x14b75524f5ffd1aaULL;
};

template<class ContainerAllocator>
struct DataType< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "pal_msgs/PoseWithVelocity";
  }

  static const char* value(const  ::pal_msgs::PoseWithVelocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
geometry_msgs/Pose2D pose\n\
float64 vx\n\
float64 vy\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const  ::pal_msgs::PoseWithVelocity_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::pal_msgs::PoseWithVelocity_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.pose);
    stream.next(m.vx);
    stream.next(m.vy);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct PoseWithVelocity_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pal_msgs::PoseWithVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::pal_msgs::PoseWithVelocity_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pose: ";
s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
  }
};


} // namespace message_operations
} // namespace ros

#endif // PAL_MSGS_MESSAGE_POSEWITHVELOCITY_H

