map_type: costmap
transform_tolerance: 0.2

inflation_radius: 0.45
footprint: [[-0.40, -0.3], [-0.4, 0.3], [0.4, 0.3],[0.4, -0.3]]
observation_sources: laser_source

laser_source: {
            data_type: LaserScan,
            topic: /scan,
            expected_update_rate: 0.4,
            observation_persistence: 0.0,
            marking: true,
            clearing: true,
            min_obstacle_height: -0.10,
            max_obstacle_height: 2.0,
            max_obstacle_range: 10.0}
