/* Auto-generated by genmsg_cpp for file /home/arturo/ros_works/roswheelchair/trunk/ros/stacks/inria_wheelchair/ghmm/msg/ProbabilisticGrid.msg */
#ifndef GHMM_MESSAGE_PROBABILISTICGRID_H
#define GHMM_MESSAGE_PROBABILISTICGRID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "nav_msgs/MapMetaData.h"

namespace ghmm
{
template <class ContainerAllocator>
struct ProbabilisticGrid_ {
  typedef ProbabilisticGrid_<ContainerAllocator> Type;

  ProbabilisticGrid_()
  : header()
  , info()
  , time_step()
  , entity(0)
  , n_steps(0)
  , data()
  {
  }

  ProbabilisticGrid_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , info(_alloc)
  , time_step()
  , entity(0)
  , n_steps(0)
  , data(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::nav_msgs::MapMetaData_<ContainerAllocator>  _info_type;
   ::nav_msgs::MapMetaData_<ContainerAllocator>  info;

  typedef ros::Duration _time_step_type;
  ros::Duration time_step;

  typedef int16_t _entity_type;
  int16_t entity;

  typedef int8_t _n_steps_type;
  int8_t n_steps;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _data_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  data;


  typedef boost::shared_ptr< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ghmm::ProbabilisticGrid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ProbabilisticGrid
typedef  ::ghmm::ProbabilisticGrid_<std::allocator<void> > ProbabilisticGrid;

typedef boost::shared_ptr< ::ghmm::ProbabilisticGrid> ProbabilisticGridPtr;
typedef boost::shared_ptr< ::ghmm::ProbabilisticGrid const> ProbabilisticGridConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::ghmm::ProbabilisticGrid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::ghmm::ProbabilisticGrid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace ghmm

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::ghmm::ProbabilisticGrid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "314d5cf59a894d0c0bb26f180ce40072";
  }

  static const char* value(const  ::ghmm::ProbabilisticGrid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x314d5cf59a894d0cULL;
  static const uint64_t static_value2 = 0x0bb26f180ce40072ULL;
};

template<class ContainerAllocator>
struct DataType< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ghmm/ProbabilisticGrid";
  }

  static const char* value(const  ::ghmm::ProbabilisticGrid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header \n\
nav_msgs/MapMetaData info\n\
duration time_step\n\
int16 entity\n\
int8 n_steps\n\
float32[] data\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: nav_msgs/MapMetaData\n\
# This hold basic information about the characterists of the OccupancyGrid\n\
\n\
# The time at which the map was loaded\n\
time map_load_time\n\
# The map resolution [m/cell]\n\
float32 resolution\n\
# Map width [cells]\n\
uint32 width\n\
# Map height [cells]\n\
uint32 height\n\
# The origin of the map [m, m, rad].  This is the real-world pose of the\n\
# cell (0,0) in the map.\n\
geometry_msgs/Pose origin\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::ghmm::ProbabilisticGrid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::ghmm::ProbabilisticGrid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::ghmm::ProbabilisticGrid_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::ghmm::ProbabilisticGrid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.info);
    stream.next(m.time_step);
    stream.next(m.entity);
    stream.next(m.n_steps);
    stream.next(m.data);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ProbabilisticGrid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ghmm::ProbabilisticGrid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::ghmm::ProbabilisticGrid_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "info: ";
s << std::endl;
    Printer< ::nav_msgs::MapMetaData_<ContainerAllocator> >::stream(s, indent + "  ", v.info);
    s << indent << "time_step: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.time_step);
    s << indent << "entity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.entity);
    s << indent << "n_steps: ";
    Printer<int8_t>::stream(s, indent + "  ", v.n_steps);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.data[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // GHMM_MESSAGE_PROBABILISTICGRID_H

